server:
  port: 8888
  servlet:
    context-path: /sell #配置访问路径为 http://localhost:8888/sell/xxxx

#druid
spring:
  druid:
    url: jdbc:mysql://192.168.1.250:3306/sell?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    maxActive: 30   #最大链接数
    maxWait: 10000  #获得链接的最大等待时间
  jpa:
    show-sql: true  #显示sql语句

jackson:
  data-format: yyyy-MM-dd HH:mm:ss #日期格式化标准
  default-property-inclusion: non_null #返回json时忽略null

wechat:
  appId: wxcec0b9e65c084712 #公众号的ID
  secret: 05a7e861c1985ced86af77fb8f7163bc  #公众号的密码
  mchId: 1529533061 #商户号(在微信支付平台查看)
  mchKey: qwertyuiopasdfghjklzxcvbnm123456 #密匙(在微信支付平台自行设置,要求32位.建议使用随机密码)
  keyPath: D:\小马聪聪向前冲\05微信点餐项目\day07\微信服务号信息_资料\证书\1529533061_20190327_cert\apiclient_cert.p12  #证书路径：退款密匙(应该这么叫吧.需要去微信支付平台下载.指定密匙的绝对地址)
  notifyUrl: http://xmccjyqs.natapp1.cc/sell/pay/notify  #支付成功之后的回调地址


